name: Update README

on:
  schedule:
    - cron: "0 17 * * 1,2,3,4,5,6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: smashah/github-activity-readme@v0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
